# Generated by Django 2.0.13 on 2019-12-29 18:21

from django.db import migrations, models
import django.db.models.deletion
import mysite.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Slug', verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, help_text='Enter subtitle', max_length=120, verbose_name='Subtitle')),
                ('sentence', models.CharField(blank=True, help_text='Enter sentence', max_length=120, verbose_name='Sentence')),
                ('description', models.TextField(help_text='Enter text', verbose_name='Text')),
                ('desc_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Select image', null=True, upload_to=mysite.common.models.upload_image_path, verbose_name='Image')),
                ('filenum', models.PositiveSmallIntegerField(default=0, help_text='File number', verbose_name='File')),
                ('urllink', models.URLField(blank=True, help_text='Enter URL link', verbose_name='URL link')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date/time of cretion', verbose_name='Date')),
                ('flag', models.BooleanField(default=False, help_text='Flag', verbose_name='Flag')),
                ('data1', models.CharField(blank=True, help_text='Enter additional data 1', max_length=50, verbose_name='Add.data1')),
                ('data2', models.CharField(blank=True, help_text='Enter additional data 2', max_length=50, verbose_name='Add.data2')),
                ('data3', models.CharField(blank=True, help_text='Enter additional data 3', max_length=50, verbose_name='Add.data3')),
                ('data4', models.CharField(blank=True, help_text='Enter additional data 4', max_length=50, verbose_name='Add.data4')),
            ],
            options={
                'verbose_name_plural': 'Page content',
                'ordering': ['id'],
                'verbose_name': 'Page content',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Select an image', null=True, upload_to=mysite.common.models.upload_image_path, verbose_name='Image')),
                ('slug', models.SlugField(default='imageslug', help_text='Slug', verbose_name='Slug')),
                ('title', models.CharField(blank=True, help_text='Enter a title', max_length=120, verbose_name='Title')),
                ('sentence', models.CharField(blank=True, help_text='Enter a sentence', max_length=120, verbose_name='Sentence')),
                ('urllink', models.URLField(blank=True, help_text='Enter URL link', verbose_name='URL link')),
                ('description', models.TextField(help_text='Enter a text', verbose_name='Text')),
                ('desc_html', models.TextField(blank=True)),
                ('data1', models.CharField(blank=True, help_text='Enter additional data 1', max_length=50, verbose_name='Add.data1')),
                ('data2', models.CharField(blank=True, help_text='Enter additional data 2', max_length=50, verbose_name='Add.data2')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.Base')),
            ],
            options={
                'verbose_name_plural': 'Additional images',
                'verbose_name': 'Additional images',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter menu title', max_length=120, unique=True, verbose_name='Title')),
                ('slug', models.CharField(help_text="Enter menu name in format: '#about'", max_length=120, unique=True, verbose_name='Slug')),
                ('mark', models.PositiveSmallIntegerField(blank=True, default=0, help_text='1-output of headers for authentic.users, 2-for unauthentic.', null=True, verbose_name='Mark')),
                ('fafa', models.CharField(blank=True, help_text="Enter icon in format: 'fa fa-cog'", max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
            ],
            options={
                'verbose_name_plural': 'Horizontal menu',
                'ordering': ['id'],
                'verbose_name': 'Horizontal menu',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='Enter submenu title', max_length=120, unique=True, verbose_name='Submenu')),
                ('subslug', models.CharField(help_text="Enter submenu name in format: '#about'", max_length=120, unique=True, verbose_name='Slug')),
                ('submark', models.PositiveSmallIntegerField(blank=True, default=0, help_text='1-Submenu will be displayed', null=True, verbose_name='Submenu mark')),
                ('subfafa', models.CharField(blank=True, help_text="Enter icon in format: 'fa fa-cog'", max_length=50, verbose_name='Submenu icon')),
                ('subcolor', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('submenu', models.ForeignKey(help_text='Select menu', on_delete=django.db.models.deletion.CASCADE, to='base.Menu', to_field='title', verbose_name='Menu')),
            ],
            options={
                'verbose_name_plural': 'Vertical submenu',
                'ordering': ['id'],
                'verbose_name': 'Vertical submenu',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='menu',
            field=models.ForeignKey(help_text='Select submenu', on_delete=django.db.models.deletion.CASCADE, to='base.SubMenu', to_field='subtitle', verbose_name='Submenu'),
        ),
    ]
