# Generated by Django 2.0.13 on 2019-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190725_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='data1',
            field=models.CharField(blank=True, help_text='Введите дополнительные данные 1', max_length=120, verbose_name='Доп.данные1'),
        ),
        migrations.AddField(
            model_name='base',
            name='data2',
            field=models.CharField(blank=True, help_text='Введите дополнительные данные 2', max_length=120, verbose_name='Доп.данные2'),
        ),
        migrations.AddField(
            model_name='base',
            name='data3',
            field=models.CharField(blank=True, help_text='Введите дополнительные данные 3', max_length=120, verbose_name='Доп.данные3'),
        ),
    ]
