# Generated by Django 2.0.13 on 2019-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190823_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='data4',
            field=models.CharField(blank=True, help_text='Введите дополнительные данные 4', max_length=30, verbose_name='Доп.данные4'),
        ),
    ]
