# Generated by Django 2.0.13 on 2019-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_base_data4'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='desc_html',
            field=models.TextField(blank=True),
        ),
    ]
