# Generated by Django 2.0.13 on 2019-08-28 19:22

from django.db import migrations, models
import mysite.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_base_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='description3',
            field=models.TextField(blank=True, help_text='Введите текст3', verbose_name='Текст3'),
        ),
        migrations.AddField(
            model_name='base',
            name='image2',
            field=models.ImageField(blank=True, help_text='Выберете изображение2', null=True, upload_to=mysite.base.models.upload_image_path, verbose_name='Изображение2'),
        ),
    ]
