# Generated by Django 2.0.13 on 2019-12-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Дополнительные изображения', 'verbose_name_plural': 'Дополнительные изображения'},
        ),
        migrations.AlterField(
            model_name='base',
            name='data1',
            field=models.CharField(blank=True, help_text='Введите доп.данные 1', max_length=50, verbose_name='Доп.данные1'),
        ),
        migrations.AlterField(
            model_name='base',
            name='data2',
            field=models.CharField(blank=True, help_text='Введите доп.данные 2', max_length=50, verbose_name='Доп.данные2'),
        ),
        migrations.AlterField(
            model_name='base',
            name='data3',
            field=models.CharField(blank=True, help_text='Введите доп.данные 3', max_length=50, verbose_name='Доп.данные3'),
        ),
        migrations.AlterField(
            model_name='base',
            name='data4',
            field=models.CharField(blank=True, help_text='Введите доп.данные 4', max_length=50, verbose_name='Доп.данные4'),
        ),
        migrations.AlterField(
            model_name='base',
            name='flag',
            field=models.BooleanField(default=False, help_text='Флаг', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='base',
            name='menu',
            field=models.ForeignKey(help_text='Выберете подменю', on_delete=django.db.models.deletion.CASCADE, to='base.SubMenu', to_field='subtitle', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='base',
            name='slug',
            field=models.SlugField(help_text='Слаг', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='base',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Введите подменю', max_length=120, verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='base',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата/время создания', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='base',
            name='urllink',
            field=models.URLField(blank=True, help_text='Введите URL ссылку', verbose_name='URL ссылка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='imageslug', help_text='Слаг', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fafa',
            field=models.CharField(blank=True, help_text="Введите иконку в формате: 'fa fa-cog'", max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='1-вывод заголовков для аутентиф.пользователей, 2-для неаутентиф.', null=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(help_text="Введите имя меню в формате: '#about'", max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Введите заголовок меню', max_length=120, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subcolor',
            field=models.CharField(blank=True, max_length=50, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subfafa',
            field=models.CharField(blank=True, help_text="Введите иконку в формате: 'fa fa-cog'", max_length=50, verbose_name='Подменю иконка'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenu',
            field=models.ForeignKey(help_text='Выберете меню', on_delete=django.db.models.deletion.CASCADE, to='base.Menu', to_field='title', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subslug',
            field=models.CharField(help_text="Введите имя подменю в формате: '#about'", max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subtitle',
            field=models.CharField(help_text='Введите заголовок подменю', max_length=120, unique=True, verbose_name='Подменю'),
        ),
    ]
