# Generated by Django 2.0.13 on 2019-12-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20191215_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='language',
        ),
        migrations.RemoveField(
            model_name='image',
            name='language',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='language',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='language',
        ),
    ]
