# Generated by Django 2.0.13 on 2019-12-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20191215_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=100)),
            ],
        ),
    ]
