# Generated by Django 2.0.13 on 2019-12-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_langinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LangInfo',
        ),
    ]
