# Generated by Django 2.0.13 on 2019-12-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='Full name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Phone')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='Content')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='Subject of inquiry')),
                ('ipaddr', models.CharField(blank=True, max_length=120, verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('flag', models.BooleanField(default=False, verbose_name='Flag')),
            ],
            options={
                'verbose_name_plural': 'Incoming messages',
                'ordering': ['id'],
                'verbose_name': 'Incoming messages',
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Full name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Phone')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Letter content')),
                ('content_html', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=120, verbose_name='Letter theme')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='Letter subject')),
                ('feedback', models.CharField(blank=True, max_length=120, verbose_name='Feedback')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('action', models.BooleanField(default=False, verbose_name='Message sent')),
                ('flag', models.BooleanField(default=False, verbose_name='Flag')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.Contact', verbose_name='Person ID')),
            ],
            options={
                'verbose_name_plural': 'Forwarded correspondence',
                'ordering': ['id'],
                'verbose_name': 'Forwarded correspondence',
            },
        ),
    ]
