# Generated by Django 2.0.13 on 2019-10-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_correspondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
