# Generated by Django 2.0.13 on 2019-10-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_auto_20191028_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.Contact', verbose_name='ID персоны'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='Содержание письма'),
        ),
    ]
