# Generated by Django 2.0.13 on 2019-10-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_auto_20191028_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Послать сообщение?'),
        ),
    ]
