# Generated by Django 2.0.13 on 2019-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_auto_20191029_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id'], 'verbose_name': 'Входящие сообщения', 'verbose_name_plural': 'Входящие сообщения'},
        ),
        migrations.AlterModelOptions(
            name='correspondence',
            options={'ordering': ['id'], 'verbose_name': 'Отправленная корреспонденция', 'verbose_name_plural': 'Отправленная корреспонденция'},
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=120, verbose_name='Предмет запроса'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Сообщение отправлено'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='theme',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тема корреспонденции'),
        ),
    ]
