# Generated by Django 2.0.13 on 2019-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_auto_20191030_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='feedback',
            field=models.CharField(blank=True, max_length=120, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='theme',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тема письма'),
        ),
    ]
