# Generated by Django 2.0.13 on 2019-12-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0010_auto_20191215_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='language',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='language',
        ),
    ]
