# Generated by Django 2.0.13 on 2019-12-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0011_auto_20191215_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id'], 'verbose_name': 'Incoming messages', 'verbose_name_plural': 'Incoming messages'},
        ),
        migrations.AlterModelOptions(
            name='correspondence',
            options={'ordering': ['id'], 'verbose_name': 'Forwarded correspondence', 'verbose_name_plural': 'Forwarded correspondence'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=120, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=120, verbose_name='Subject of inquiry'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Message sent'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='content',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Letter content'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='feedback',
            field=models.CharField(blank=True, max_length=120, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.Contact', verbose_name='Person ID'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='subject',
            field=models.CharField(blank=True, max_length=120, verbose_name='Letter subject'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='theme',
            field=models.CharField(blank=True, max_length=120, verbose_name='Letter theme'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
