# Generated by Django 2.0.13 on 2019-12-29 18:21

import clients.models.clients
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID Number', primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=120, verbose_name='Company name')),
                ('slug', models.SlugField(help_text='Slug', verbose_name='Slug')),
                ('country', models.CharField(choices=[('Russia', 'Russia'), ('USA', 'USA'), ('Canada', 'Canada'), ('England', 'England'), ('Germany', 'Germany'), ('China', 'China')], default='Russia', max_length=120, verbose_name='Country')),
                ('address', models.CharField(blank=True, default='Unknown', max_length=240, verbose_name='Company address')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Company email')),
                ('email2', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Contact email')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Phone')),
                ('about', models.TextField(blank=True, default='', max_length=500, verbose_name='About company')),
                ('area', models.CharField(choices=[('Manufacture', 'Manufacture'), ('Retail', 'Retail'), ('Installation', 'Installation'), ('Science', 'Science')], default='Manufacture', max_length=120, verbose_name='Area')),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], default='HVAC', help_text='Select emailing category', max_length=30, verbose_name='Category')),
                ('language', models.CharField(choices=[('RU', 'RU'), ('EN', 'EN')], default='RU', help_text='Select emailing language', max_length=30, verbose_name='Language')),
                ('persons', models.CharField(blank=True, default='', max_length=120, verbose_name='Company persons')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_post', models.DateTimeField(blank=True, null=True, verbose_name='Last post')),
                ('enable_mailing', models.BooleanField(default=True, verbose_name='Emailing')),
                ('interested', models.BooleanField(default=False, verbose_name='Interest')),
                ('preorder', models.BooleanField(default=False, verbose_name='Preorder')),
                ('counter', models.PositiveSmallIntegerField(default=0, help_text='Number of tick made', verbose_name='Tick counter')),
                ('count', models.PositiveSmallIntegerField(default=0, help_text='Number of email sent', verbose_name='Email counter')),
                ('bid', models.PositiveIntegerField(default=0, help_text='Bid made by client', verbose_name='Bid')),
                ('error_mailing', models.CharField(blank=True, default='', max_length=360, verbose_name='Emailing report')),
                ('file', models.FileField(blank=True, help_text='File from client', null=True, upload_to=clients.models.clients.upload_image_path, verbose_name='File')),
                ('filepath', models.CharField(blank=True, max_length=120, verbose_name='Path to downloaded files')),
                ('flag', models.BooleanField(default=False, verbose_name='Flag')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ImportDuplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=120, verbose_name='Company name')),
                ('cause', models.TextField(blank=True, default='', max_length=500, verbose_name='Cause of Import Duplication')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('flag', models.BooleanField(default=False, verbose_name='Flag')),
            ],
            options={
                'verbose_name_plural': 'ImportDuplication',
                'verbose_name': 'ImportDuplication',
            },
        ),
    ]
