# Generated by Django 2.0.13 on 2019-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='Имя компании')),
                ('email', models.EmailField(max_length=120, verbose_name='Эл.почта')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Телефон')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='О компании')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='Сфера деятельности')),
                ('persons', models.CharField(blank=True, max_length=120, verbose_name='Лица компании')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('enable_mailing', models.BooleanField(default=True, verbose_name='Разрешить рассылку')),
                ('interested', models.BooleanField(default=False, verbose_name='Клиент заинтересован')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'ordering': ['id'],
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
