# Generated by Django 2.0.13 on 2019-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Clients',
        ),
    ]
