# Generated by Django 2.0.13 on 2019-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20191101_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='category',
            field=models.CharField(choices=[('server', 'Server'), ('facebook', 'Facebook'), ('mathematics', 'Mathematics')], default='HVAC', help_text='Выберете категорию деятельности', max_length=30, verbose_name='Категория'),
        ),
    ]
