# Generated by Django 2.0.13 on 2019-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191106_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0, help_text='Количество оправленных писем', verbose_name='Счетчик  отправок'),
        ),
    ]
