# Generated by Django 2.0.13 on 2019-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20191106_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='error_mailing',
            field=models.CharField(blank=True, default='Ошибок нет', max_length=360, verbose_name='Отчет об ошибке отправки'),
        ),
    ]
