# Generated by Django 2.0.13 on 2019-11-09 20:50

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clients_error_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='file',
            field=models.FileField(blank=True, help_text='Файл данных от клиента', null=True, upload_to=clients.models.upload_image_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='Эл.почта'),
        ),
    ]
