# Generated by Django 2.0.13 on 2019-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20191110_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='address',
            field=models.CharField(blank=True, max_length=240, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='clients',
            name='email2',
            field=models.EmailField(default='', max_length=120, unique=True, verbose_name='Эл.почта2'),
            preserve_default=False,
        ),
    ]
