# Generated by Django 2.0.13 on 2019-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20191110_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email2',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Эл.почта2'),
        ),
    ]
