# Generated by Django 2.0.13 on 2019-11-14 18:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20191110_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='file',
            field=models.FileField(blank=True, help_text='Файл данных от клиента', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='', verbose_name='Файл'),
        ),
    ]
