# Generated by Django 2.0.13 on 2019-11-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clients_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='filepath',
        ),
    ]
