# Generated by Django 2.0.13 on 2019-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_clients_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='filepath',
            field=models.CharField(blank=True, max_length=120, verbose_name='Путь в папке загр.файлов'),
        ),
    ]
