# Generated by Django 2.0.13 on 2019-11-16 14:56

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_clients_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='preorder',
            field=models.BooleanField(default=False, verbose_name='Предзаказ'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='enable_mailing',
            field=models.BooleanField(default=True, verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='file',
            field=models.FileField(blank=True, help_text='Файл данных клиента', null=True, upload_to=clients.models.upload_image_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='interested',
            field=models.BooleanField(default=False, verbose_name='Интерес'),
        ),
    ]
