# Generated by Django 2.0.13 on 2019-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_clients_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='error_mailing',
            field=models.CharField(blank=True, default='None', max_length=360, verbose_name='Отчет об ошибке отправки'),
        ),
    ]
