# Generated by Django 2.0.13 on 2019-12-17 09:56

import clients.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20191212_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(blank=True, max_length=240, verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='area',
            field=models.CharField(blank=True, max_length=120, verbose_name='Field of activity'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], default='HVAC', help_text='Select category', max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='company',
            field=models.CharField(max_length=120, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of email sent', verbose_name='Email counter'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='Company email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email2',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='enable_mailing',
            field=models.BooleanField(default=True, verbose_name='Emailing'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='error_mailing',
            field=models.CharField(blank=True, default='None', max_length=360, verbose_name='Emailing report'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='file',
            field=models.FileField(blank=True, help_text='File from client', null=True, upload_to=clients.models.upload_image_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='filepath',
            field=models.CharField(blank=True, max_length=120, verbose_name='Path to downloaded files'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='interested',
            field=models.BooleanField(default=False, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='language',
            field=models.CharField(choices=[('RU', 'RU'), ('EN', 'EN')], default='RU', help_text='Select language', max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='persons',
            field=models.CharField(blank=True, max_length=120, verbose_name='Company persons'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='preorder',
            field=models.BooleanField(default=False, verbose_name='Preorder'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(help_text='Slug', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID Number', primary_key=True, serialize=False),
        ),
    ]
