# Generated by Django 2.0.13 on 2019-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20191217_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='bid',
            field=models.PositiveIntegerField(default=0, help_text='Bid made by client', verbose_name='Bid'),
        ),
    ]
