# Generated by Django 2.0.13 on 2019-12-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_clients_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='bid',
            field=models.PositiveIntegerField(default=10000, help_text='Bid made by client', verbose_name='Bid'),
        ),
    ]
