# Generated by Django 2.0.13 on 2019-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20191221_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About company'),
        ),
    ]
