# Generated by Django 2.0.13 on 2019-12-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20191222_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='about',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='error_mailing',
            field=models.CharField(blank=True, default='', max_length=360, verbose_name='Emailing report'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='persons',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Company persons'),
        ),
    ]
