# Generated by Django 2.0.13 on 2019-12-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20191222_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='bid',
            field=models.PositiveIntegerField(default=0, help_text='Bid made by client', verbose_name='Bid'),
        ),
    ]
