# Generated by Django 2.0.13 on 2019-12-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20191223_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Country'),
        ),
    ]
