# Generated by Django 2.0.13 on 2019-10-06 16:19

from django.db import migrations, models
import mysite.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='image',
            field=models.ImageField(blank=True, default='image/no_image.jpg', help_text='Выберете изображение', null=True, upload_to=mysite.base.models.upload_image_path, verbose_name='Изображение'),
        ),
    ]
