# Generated by Django 2.0.13 on 2019-10-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20191014_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
