# Generated by Django 2.0.13 on 2019-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20191101_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Изображения дополнительно', 'verbose_name_plural': 'Изображения дополнительно'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics')], default='HVAC', help_text='Выберете категорию деятельности', max_length=30, unique=True, verbose_name='Категория'),
        ),
    ]
