# Generated by Django 2.0.13 on 2019-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20191130_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='language',
            field=models.CharField(choices=[('RU', 'ru'), ('EN', 'en')], default='RU', help_text='Выберете язык', max_length=30, verbose_name='Язык'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('category', 'language')},
        ),
    ]
