# Generated by Django 2.0.13 on 2019-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_auto_20191206_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='language',
            field=models.CharField(choices=[('RU', 'RU'), ('EN', 'EN')], default='RU', help_text='Выберете язык', max_length=30, verbose_name='Язык'),
        ),
    ]
