# Generated by Django 2.0.13 on 2019-12-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_auto_20191206_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['category', 'language'], 'verbose_name': 'Продвижение', 'verbose_name_plural': 'Продвижение'},
        ),
    ]
