# Generated by Django 2.0.13 on 2019-12-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_image_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='language',
        ),
    ]
