# Generated by Django 2.0.13 on 2019-10-06 14:38

from django.db import migrations, models
import django.db.models.deletion
import mysite.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок контекста', max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Слаг..', verbose_name='Слаг')),
                ('subtitle', models.CharField(blank=True, help_text='Введите подзаголовок контекста', max_length=120, verbose_name='Подзаголовок')),
                ('sentence', models.CharField(blank=True, help_text='Введите предложение', max_length=120, verbose_name='Предложение')),
                ('description', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('desc_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Выберете изображение', null=True, upload_to=mysite.base.models.upload_image_path, verbose_name='Изображение')),
                ('filenum', models.PositiveSmallIntegerField(default=0, help_text='Номер файла', verbose_name='Файл')),
                ('urllink', models.URLField(blank=True, help_text='Введите ссылку на ресурс', verbose_name='Ссылка')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Дата/время создания контекста', verbose_name='Дата')),
                ('flag', models.BooleanField(default=False, help_text='Флаг..', verbose_name='Флаг')),
                ('data1', models.CharField(blank=True, help_text='Введите дополнительные данные 1', max_length=50, verbose_name='Доп.данные1')),
                ('data2', models.CharField(blank=True, help_text='Введите дополнительные данные 2', max_length=50, verbose_name='Доп.данные2')),
                ('data3', models.CharField(blank=True, help_text='Введите дополнительные данные 3', max_length=50, verbose_name='Доп.данные3')),
                ('data4', models.CharField(blank=True, help_text='Введите дополнительные данные 4', max_length=50, verbose_name='Доп.данные4')),
            ],
            options={
                'verbose_name_plural': 'Содержание страницы',
                'ordering': ['id'],
                'verbose_name': 'Содержание страницы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=120, verbose_name='Эл.почта')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Телефон')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='Содержание')),
                ('ipaddr', models.CharField(blank=True, max_length=120, verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
                'verbose_name': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Выберете изображение', null=True, upload_to=mysite.base.models.upload_image_path, verbose_name='Изображение')),
                ('slug', models.SlugField(default='imageslug', help_text='Слаг..', verbose_name='Слаг')),
                ('title', models.CharField(blank=True, help_text='Введите подзаголовок', max_length=120, verbose_name='Подзаголовок')),
                ('sentence', models.CharField(blank=True, help_text='Введите предложение', max_length=120, verbose_name='Предложение')),
                ('description', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.Base')),
            ],
            options={
                'verbose_name_plural': 'Изображения дополнительно',
                'verbose_name': 'Изображения дополнительно',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название раздела меню', max_length=120, unique=True, verbose_name='Заголовок')),
                ('slug', models.CharField(help_text="Введите раздел меню латинницей в формате: '#about'", max_length=120, unique=True, verbose_name='Слаг')),
                ('mark', models.PositiveSmallIntegerField(blank=True, default=0, help_text='1-вывод заголовков для аутентиф. пользователей, 2-для неаутентиф.', null=True, verbose_name='Метка')),
                ('fafa', models.CharField(blank=True, help_text="Ввод иконки в формате 'fa fa-cog'", max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name_plural': 'Горизонтальное меню',
                'ordering': ['id'],
                'verbose_name': 'Горизонтальное меню',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='Введите название раздела подменю', max_length=120, unique=True, verbose_name='Подменю')),
                ('subslug', models.CharField(help_text="Введите подменю латинницей в формате: '#about'", max_length=120, unique=True, verbose_name='Слаг')),
                ('submark', models.PositiveSmallIntegerField(blank=True, default=0, help_text='1-подменю будет выведено', null=True, verbose_name='Метка подменю')),
                ('subfafa', models.CharField(blank=True, help_text="Ввод иконки в формате 'fa fa-cog'", max_length=50, verbose_name='Иконка подменю')),
                ('subcolor', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('submenu', models.ForeignKey(help_text='Выберете раздел меню', on_delete=django.db.models.deletion.CASCADE, to='base.Menu', to_field='title', verbose_name='Меню')),
            ],
            options={
                'verbose_name_plural': 'Вертикальное подменю',
                'ordering': ['id'],
                'verbose_name': 'Вертикальное подменю',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='menu',
            field=models.ForeignKey(help_text='Выберете раздел подменю', on_delete=django.db.models.deletion.CASCADE, to='base.SubMenu', to_field='subtitle', verbose_name='Подменю'),
        ),
    ]
