# Generated by Django 2.0.13 on 2019-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], help_text='Select category name', max_length=30, unique=True, verbose_name='Category')),
                ('tick', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter ticks number, 1 tick-1 hour, 0-stop', null=True, verbose_name='Ticks')),
                ('counter', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Tick count', null=True, verbose_name='Tick counter')),
                ('event', models.CharField(blank=True, help_text='Scheduler status', max_length=120, null=True, verbose_name='Status')),
                ('processing', models.CharField(default='None', help_text='Processing time', max_length=120, null=True, verbose_name='Processing')),
            ],
            options={
                'verbose_name_plural': 'Scheduler',
                'ordering': ['id'],
                'verbose_name': 'Scheduler',
            },
        ),
    ]
