# Generated by Django 2.0.13 on 2019-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='counter',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Подсчет тиков', null=True, verbose_name='Счетчик тиков'),
        ),
    ]
