# Generated by Django 2.0.13 on 2019-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20191101_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
