# Generated by Django 2.0.13 on 2019-11-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20191109_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='event',
            field=models.CharField(blank=True, help_text='События в планировщике', max_length=120, null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], help_text='Выберете название категории', max_length=30, unique=True, verbose_name='Категория рассылки'),
        ),
    ]
