# Generated by Django 2.0.13 on 2019-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20191130_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='processing',
            field=models.CharField(default='None', help_text='Время обработки', max_length=120, null=True, verbose_name='Обработка'),
        ),
    ]
