# Generated by Django 2.0.13 on 2019-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_scheduler_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={'ordering': ['id'], 'verbose_name': 'Панировщик', 'verbose_name_plural': 'Панировщик'},
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], help_text='Выберете категорию', max_length=30, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='counter',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Число тиков', null=True, verbose_name='Счетчик тиков'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='event',
            field=models.CharField(blank=True, help_text='Статус планировщика', max_length=120, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='tick',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Введите число тиков, 1 тик-1 час, 0-стоп', null=True, verbose_name='Тики'),
        ),
    ]
