# Generated by Django 2.0.13 on 2019-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_remove_scheduler_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={'ordering': ['id'], 'verbose_name': 'Scheduler', 'verbose_name_plural': 'Scheduler'},
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Smart Home', 'Smart Home'), ('IoT', 'IoT'), ('Facebook', 'Facebook'), ('Mathematics', 'Mathematics'), ('SFUGD', 'SFUGD')], help_text='Select category name', max_length=30, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='counter',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Tick count', null=True, verbose_name='Tick counter'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='event',
            field=models.CharField(blank=True, help_text='Scheduler status', max_length=120, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='processing',
            field=models.CharField(default='None', help_text='Processing time', max_length=120, null=True, verbose_name='Processing'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='tick',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Enter ticks number, 1 tick-1 hour, 0-stop', null=True, verbose_name='Ticks'),
        ),
    ]
